-- Nordic Atlas Packaging — schema afledt af analyse/er-diagram.md
-- Skemaet er på 3. normalform, jf. dokumentation i ER-diagrammet.

DROP TABLE IF EXISTS follow_up CASCADE;
DROP TABLE IF EXISTS inquiry CASCADE;
DROP TABLE IF EXISTS mockup CASCADE;
DROP TABLE IF EXISTS product_specification CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS logo CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS admin CASCADE;

CREATE TABLE customer (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name    VARCHAR(200) NOT NULL,
    cvr             VARCHAR(8) UNIQUE NOT NULL,
    contact_person  VARCHAR(200),
    email           VARCHAR(255) NOT NULL,
    phone           VARCHAR(50),
    address         VARCHAR(500),
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE admin (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(200) NOT NULL,
    email           VARCHAR(255) UNIQUE NOT NULL,
    password_hash   VARCHAR(255) NOT NULL,
    role            VARCHAR(50) NOT NULL DEFAULT 'admin',
    created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE logo (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id      BIGINT,
    filename         VARCHAR(500) NOT NULL,
    file_path        VARCHAR(1000) NOT NULL,
    file_size_bytes  BIGINT NOT NULL,
    mime_type        VARCHAR(100) NOT NULL,
    uploaded_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL
);

CREATE TABLE product (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200) NOT NULL,
    type         VARCHAR(50) NOT NULL,
    base_price   DECIMAL(10, 2) NOT NULL,
    description  VARCHAR(2000)
);

CREATE TABLE product_specification (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id    BIGINT NOT NULL,
    category      VARCHAR(50) NOT NULL,
    spec_value    VARCHAR(100) NOT NULL,
    price_factor  DECIMAL(5, 3) NOT NULL DEFAULT 1.000,
    FOREIGN KEY (product_id) REFERENCES product(id) ON DELETE CASCADE
);

CREATE TABLE mockup (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id              BIGINT,
    product_id               BIGINT NOT NULL,
    logo_id                  BIGINT NOT NULL,
    file_path                VARCHAR(1000) NOT NULL,
    selected_specifications  VARCHAR(2000),
    generated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE SET NULL,
    FOREIGN KEY (product_id)  REFERENCES product(id),
    FOREIGN KEY (logo_id)     REFERENCES logo(id)
);

CREATE TABLE inquiry (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  BIGINT NOT NULL,
    mockup_id    BIGINT,
    inquiry_type VARCHAR(30) NOT NULL DEFAULT 'designer',
    quantity     INT,
    total_price  DECIMAL(12, 2),
    status       VARCHAR(30) NOT NULL DEFAULT 'new'
                 CHECK (status IN ('new', 'in_progress', 'answered', 'won', 'lost', 'closed')),
    notes        VARCHAR(2000),
    created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id),
    FOREIGN KEY (mockup_id)   REFERENCES mockup(id) ON DELETE SET NULL
);

CREATE TABLE follow_up (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT NOT NULL,
    admin_id      BIGINT NOT NULL,
    planned_date  DATE NOT NULL,
    type          VARCHAR(30) NOT NULL,
    status        VARCHAR(30) NOT NULL DEFAULT 'planned'
                  CHECK (status IN ('planned', 'completed', 'cancelled')),
    notes         VARCHAR(2000),
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at  TIMESTAMP,
    FOREIGN KEY (customer_id) REFERENCES customer(id) ON DELETE CASCADE,
    FOREIGN KEY (admin_id)    REFERENCES admin(id)
);
